/* tslint:disable */
/* eslint-disable */
/**
 * BIDS WebRTC Signaling API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApplicationInfo,
} from '../models/index';
import {
    ApplicationInfoFromJSON,
    ApplicationInfoToJSON,
} from '../models/index';

export interface GetApplicationInfoRequest {
    appId: string;
}

/**
 * 
 */
export class ApplicationManagementApi extends runtime.BaseAPI {

    /**
     * IDを指定してアプリケーションの情報を取得する 
     * Applicationの情報を取得する
     */
    async getApplicationInfoRaw(requestParameters: GetApplicationInfoRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApplicationInfo>> {
        if (requestParameters['appId'] == null) {
            throw new runtime.RequiredError(
                'appId',
                'Required parameter "appId" was null or undefined when calling getApplicationInfo().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/apps/{appId}`.replace(`{${"appId"}}`, encodeURIComponent(String(requestParameters['appId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApplicationInfoFromJSON(jsonValue));
    }

    /**
     * IDを指定してアプリケーションの情報を取得する 
     * Applicationの情報を取得する
     */
    async getApplicationInfo(requestParameters: GetApplicationInfoRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApplicationInfo> {
        const response = await this.getApplicationInfoRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
