/* tslint:disable */
/* eslint-disable */
/**
 * BIDS WebRTC Signaling API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiInfo
 */
export interface ApiInfo {
    /**
     * サーバの名前
     * @type {string}
     * @memberof ApiInfo
     */
    readonly serverName?: string;
    /**
     * APIのバージョン
     * @type {string}
     * @memberof ApiInfo
     */
    readonly version?: string;
}

/**
 * Check if a given object implements the ApiInfo interface.
 */
export function instanceOfApiInfo(value: object): value is ApiInfo {
    return true;
}

export function ApiInfoFromJSON(json: any): ApiInfo {
    return ApiInfoFromJSONTyped(json, false);
}

export function ApiInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'serverName': json['server_name'] == null ? undefined : json['server_name'],
        'version': json['version'] == null ? undefined : json['version'],
    };
}

  export function ApiInfoToJSON(json: any): ApiInfo {
      return ApiInfoToJSONTyped(json, false);
  }

  export function ApiInfoToJSONTyped(value?: Omit<ApiInfo, 'server_name'|'version'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
    };
}

