/* tslint:disable */
/* eslint-disable */
/**
 * BIDS WebRTC Signaling API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ClientInfoWithToken
 */
export interface ClientInfoWithToken {
    /**
     * アプリID
     * 
     * @type {string}
     * @memberof ClientInfoWithToken
     */
    readonly appId: string;
    /**
     * クライアントID
     * 
     * @type {string}
     * @memberof ClientInfoWithToken
     */
    readonly clientId: string;
    /**
     * 名前
     * 
     * @type {string}
     * @memberof ClientInfoWithToken
     */
    name: string;
    /**
     * 作成日時
     * 
     * @type {Date}
     * @memberof ClientInfoWithToken
     */
    readonly createdAt: Date;
    /**
     * リフレッシュトークン
     * 
     * @type {string}
     * @memberof ClientInfoWithToken
     */
    readonly refreshToken: string;
}

/**
 * Check if a given object implements the ClientInfoWithToken interface.
 */
export function instanceOfClientInfoWithToken(value: object): value is ClientInfoWithToken {
    if (!('appId' in value) || value['appId'] === undefined) return false;
    if (!('clientId' in value) || value['clientId'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('refreshToken' in value) || value['refreshToken'] === undefined) return false;
    return true;
}

export function ClientInfoWithTokenFromJSON(json: any): ClientInfoWithToken {
    return ClientInfoWithTokenFromJSONTyped(json, false);
}

export function ClientInfoWithTokenFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClientInfoWithToken {
    if (json == null) {
        return json;
    }
    return {
        
        'appId': json['app_id'],
        'clientId': json['client_id'],
        'name': json['name'],
        'createdAt': (new Date(json['created_at'])),
        'refreshToken': json['refresh_token'],
    };
}

  export function ClientInfoWithTokenToJSON(json: any): ClientInfoWithToken {
      return ClientInfoWithTokenToJSONTyped(json, false);
  }

  export function ClientInfoWithTokenToJSONTyped(value?: Omit<ClientInfoWithToken, 'app_id'|'client_id'|'created_at'|'refresh_token'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
    };
}

