/* tslint:disable */
/* eslint-disable */
/**
 * BIDS WebRTC Signaling API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ClientInfo
 */
export interface ClientInfo {
    /**
     * アプリID
     * 
     * @type {string}
     * @memberof ClientInfo
     */
    readonly appId: string;
    /**
     * クライアントID
     * 
     * @type {string}
     * @memberof ClientInfo
     */
    readonly clientId?: string;
    /**
     * 名前
     * 
     * @type {string}
     * @memberof ClientInfo
     */
    name?: string;
    /**
     * 作成日時
     * 
     * @type {Date}
     * @memberof ClientInfo
     */
    readonly createdAt?: Date;
    /**
     * 最終利用日時
     * 
     * @type {Date}
     * @memberof ClientInfo
     */
    readonly lastUsedAt?: Date;
}

/**
 * Check if a given object implements the ClientInfo interface.
 */
export function instanceOfClientInfo(value: object): value is ClientInfo {
    if (!('appId' in value) || value['appId'] === undefined) return false;
    return true;
}

export function ClientInfoFromJSON(json: any): ClientInfo {
    return ClientInfoFromJSONTyped(json, false);
}

export function ClientInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClientInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'appId': json['app_id'],
        'clientId': json['client_id'] == null ? undefined : json['client_id'],
        'name': json['name'] == null ? undefined : json['name'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'lastUsedAt': json['last_used_at'] == null ? undefined : (new Date(json['last_used_at'])),
    };
}

  export function ClientInfoToJSON(json: any): ClientInfo {
      return ClientInfoToJSONTyped(json, false);
  }

  export function ClientInfoToJSONTyped(value?: Omit<ClientInfo, 'app_id'|'client_id'|'created_at'|'last_used_at'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
    };
}

