/* tslint:disable */
/* eslint-disable */
/**
 * BIDS WebRTC Signaling API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetClientInfoList401Response
 */
export interface GetClientInfoList401Response {
    /**
     * 
     * @type {string}
     * @memberof GetClientInfoList401Response
     */
    message: string;
}

/**
 * Check if a given object implements the GetClientInfoList401Response interface.
 */
export function instanceOfGetClientInfoList401Response(value: object): value is GetClientInfoList401Response {
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function GetClientInfoList401ResponseFromJSON(json: any): GetClientInfoList401Response {
    return GetClientInfoList401ResponseFromJSONTyped(json, false);
}

export function GetClientInfoList401ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetClientInfoList401Response {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
    };
}

  export function GetClientInfoList401ResponseToJSON(json: any): GetClientInfoList401Response {
      return GetClientInfoList401ResponseToJSONTyped(json, false);
  }

  export function GetClientInfoList401ResponseToJSONTyped(value?: GetClientInfoList401Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
    };
}

