/* tslint:disable */
/* eslint-disable */
/**
 * BIDS WebRTC Signaling API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Offerしたクライアントのロール
 * 
 * @export
 */
export const OfferClientRole = {
    Provider: 'provider',
    Subscriber: 'subscriber'
} as const;
export type OfferClientRole = typeof OfferClientRole[keyof typeof OfferClientRole];


export function instanceOfOfferClientRole(value: any): boolean {
    for (const key in OfferClientRole) {
        if (Object.prototype.hasOwnProperty.call(OfferClientRole, key)) {
            if (OfferClientRole[key as keyof typeof OfferClientRole] === value) {
                return true;
            }
        }
    }
    return false;
}

export function OfferClientRoleFromJSON(json: any): OfferClientRole {
    return OfferClientRoleFromJSONTyped(json, false);
}

export function OfferClientRoleFromJSONTyped(json: any, ignoreDiscriminator: boolean): OfferClientRole {
    return json as OfferClientRole;
}

export function OfferClientRoleToJSON(value?: OfferClientRole | null): any {
    return value as any;
}

export function OfferClientRoleToJSONTyped(value: any, ignoreDiscriminator: boolean): OfferClientRole {
    return value as OfferClientRole;
}

