/* tslint:disable */
/* eslint-disable */
/**
 * BIDS WebRTC Signaling API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OfferClientRole } from './OfferClientRole';
import {
    OfferClientRoleFromJSON,
    OfferClientRoleFromJSONTyped,
    OfferClientRoleToJSON,
    OfferClientRoleToJSONTyped,
} from './OfferClientRole';

/**
 * 
 * @export
 * @interface PostSDPOfferInfoRequestBody
 */
export interface PostSDPOfferInfoRequestBody {
    /**
     * 
     * @type {OfferClientRole}
     * @memberof PostSDPOfferInfoRequestBody
     */
    role: OfferClientRole;
    /**
     * Offer SDP (Base64 encoded)
     * 
     * @type {string}
     * @memberof PostSDPOfferInfoRequestBody
     */
    offer: string;
    /**
     * 既に接続が確立されているクライアントのIDのリスト
     * 
     * @type {Array<string>}
     * @memberof PostSDPOfferInfoRequestBody
     */
    establishedClients?: Array<string>;
}



/**
 * Check if a given object implements the PostSDPOfferInfoRequestBody interface.
 */
export function instanceOfPostSDPOfferInfoRequestBody(value: object): value is PostSDPOfferInfoRequestBody {
    if (!('role' in value) || value['role'] === undefined) return false;
    if (!('offer' in value) || value['offer'] === undefined) return false;
    return true;
}

export function PostSDPOfferInfoRequestBodyFromJSON(json: any): PostSDPOfferInfoRequestBody {
    return PostSDPOfferInfoRequestBodyFromJSONTyped(json, false);
}

export function PostSDPOfferInfoRequestBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostSDPOfferInfoRequestBody {
    if (json == null) {
        return json;
    }
    return {
        
        'role': OfferClientRoleFromJSON(json['role']),
        'offer': json['offer'],
        'establishedClients': json['established_clients'] == null ? undefined : json['established_clients'],
    };
}

  export function PostSDPOfferInfoRequestBodyToJSON(json: any): PostSDPOfferInfoRequestBody {
      return PostSDPOfferInfoRequestBodyToJSONTyped(json, false);
  }

  export function PostSDPOfferInfoRequestBodyToJSONTyped(value?: PostSDPOfferInfoRequestBody | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'role': OfferClientRoleToJSON(value['role']),
        'offer': value['offer'],
        'established_clients': value['establishedClients'],
    };
}

