/* tslint:disable */
/* eslint-disable */
/**
 * BIDS WebRTC Signaling API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SDPAnswerInfo
 */
export interface SDPAnswerInfo {
    /**
     * SDP ID
     * 
     * @type {string}
     * @memberof SDPAnswerInfo
     */
    sdpId: string;
    /**
     * 名前
     * 
     * @type {string}
     * @memberof SDPAnswerInfo
     */
    readonly answerClientId: string;
    /**
     * Answer SDP (Base64 encoded)
     * 
     * @type {string}
     * @memberof SDPAnswerInfo
     */
    answer: string;
}

/**
 * Check if a given object implements the SDPAnswerInfo interface.
 */
export function instanceOfSDPAnswerInfo(value: object): value is SDPAnswerInfo {
    if (!('sdpId' in value) || value['sdpId'] === undefined) return false;
    if (!('answerClientId' in value) || value['answerClientId'] === undefined) return false;
    if (!('answer' in value) || value['answer'] === undefined) return false;
    return true;
}

export function SDPAnswerInfoFromJSON(json: any): SDPAnswerInfo {
    return SDPAnswerInfoFromJSONTyped(json, false);
}

export function SDPAnswerInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SDPAnswerInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'sdpId': json['sdp_id'],
        'answerClientId': json['answer_client_id'],
        'answer': json['answer'],
    };
}

  export function SDPAnswerInfoToJSON(json: any): SDPAnswerInfo {
      return SDPAnswerInfoToJSONTyped(json, false);
  }

  export function SDPAnswerInfoToJSONTyped(value?: Omit<SDPAnswerInfo, 'answer_client_id'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'sdp_id': value['sdpId'],
        'answer': value['answer'],
    };
}

